### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by foralliance** [Hwang64/MLKP#1]
lib下make时，提示：
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
rm -rf build

进而导致test时候，提示：
Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from fast_rcnn.test import test_net
  File "/home/jmx/MLKP/tools/../lib/fast_rcnn/test.py", line 17, in <module>
    from fast_rcnn.nms_wrapper import nms, soft_nms
  File "/home/jmx/MLKP/tools/../lib/fast_rcnn/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

请问该如何解决？？

**Comment by Hwang64** [comment]
remove the file cpu_nms.so and gpu_nms.so in lib/nms/, and rebuild the Cython in lib.

**Comment by moyans** [comment]
@foralliance The error  ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory
maybe you cuda is 8.0 version，you can use this lines solve it.
` sudo ln -sf /usr/local/cuda/lib64/libcudart.so.8.0 /usr/local/cuda/lib64/libcudart.so.7.5 `

**Comment by foralliance** [comment]
@moyans 
谢谢您，按照作者提供的方法，我已经解决了上述问题．

**Comment by guobinli** [comment]
@foralliance你好，我也遇到同样的问题，请问是怎么解决的呢？
