### ISSUE TITLE
test erro

### ISSUE THREAD

**Issue by moyans** [Hwang64/MLKP#6]
@Hwang64 when i test the model on own dataset:
`python ./tools/test_net.py --gpu 1 --def models/VGG16/test.prototxt --net output/faster_rcnn_end2end/voc_2007_trainval/vgg16_mlkp_iter_2000.caffemodel --imdb voc_2007_test --cfg experiments/cfgs/faster_rcnn_end2end.yml`
get this erro:
```
I0605 15:57:31.425818 15554 net.cpp:816] Ignoring source layer loss_cls
I0605 15:57:31.425822 15554 net.cpp:816] Ignoring source layer loss_bbox
I0605 15:57:31.425825 15554 net.cpp:816] Ignoring source layer accuarcy
Traceback (most recent call last):
  File "./tools/test_net.py", line 89, in <module>
    model_type=modelObj.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
how can i solve it?

**Comment by UeFan** [comment]
Hi,  i'm facing the same erro, could you point out what's wrong?

**Comment by UeFan** [comment]
I got it.
The caffemodel name need to be modified after download.

According to [https://github.com/Hwang64/MLKP/blob/164524f3631e46feb16a1559be38ff589ddf9377/tools/test_net.py#L88](url)

The caffemodel should be somthing like this
rresnet_faster_rcnn_voc07_iter_70000.caffemodel
